---
- name: Playbook to create test gce instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ["Set here the email account"]
    credentials_file: ["Put here the credentials file .json"]
    project_id: ["Put here your ID Project"]
    instance_names: ["Put here the name of instances to create"]
    machine_type: n1-standard-1 ---> "Example"
    image: centos-7 -----> "Example"

  tasks:
    - name: Launch instances
      gce:
        instance_names: test1
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata: '{"sshKeys":"Put here your key"}'
