---
- name: Playbook to create gce load balancing instance
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    service_account_email: acalleja@tam-blog.iam.gserviceaccount.com
    credentials_file: tam-blog-f41fc56a41a2.json
    project_id: tam-blog

  tasks:
    - name: Create gce load balancer
      gce_lb:
        name: lbserver
        state: present
        region: us-central1
        members: ['us-central1-a/web1','us-central1-a/web2','us-central1-a/web3']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
