---
- name: Create gce webserver instances
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    service_account_email: acalleja@tam-blog.iam.gserviceaccount.com
    credentials_file: tam-blog-f41fc56a41a2.json
    project_id: tam-blog
    instance_names: web1,web2,web3
    machine_type: n1-standard-1
    image: centos-7

  tasks:
  - name: Create firewall rule to allow http traffic
    gce_net:
      name: default
      fwname: "my-http-fw-rule"
      allowed: tcp:80
      state: present
      src_range: "0.0.0.0/0"
      target_tags: "http-server"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"

  - name: Create instances based on image {{ image }}
    gce:
      instance_names: "{{ instance_names }}"
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      state: present
      preemptible: true
      tags: http-server
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      metadata: '{"sshKeys":"dark_axl:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDgkDNPD18cIbZJlhhntzj2Mms8cGJ+cE1cs1i8rBrfbxhDKZWZW+4UGdw5y+k2SY/ieu+084zHxeSMPXVCUSbLA3VHNldizCZkj4qn5VC1Wr9EWS901gaKCV5+u06p8z2kOXyFZbbavkumb7AcediGvr2d2u8kV45uVv/nDoiXea/5UIJ6p0t37nLWRk4drLhTF9AHbOtfcmuKI3pJ9DyInWtM+NYyCrl1xd3jaHLw6iqKdn5EfZSEowXCayuatW8xj9I50NuTH3TSLdScDkQJovs7mI9+VAQ7tlOp54iEcs5TtHMzTsKTYwSis5YYQOvvKIRitXSg6/qO6OaDsmjydLOjOUQ7K52T8P+tjgtobdBc2ITkagMN5y9mRD09Gie02P8+vkEdCJy6aZswKM+QPmcUuM7l+v56jgkpJrgcgvrLlDHsxWIXdoH+PLQ6GAMUcZ5bdtfviW5bGyN+VESm/fksjHUNkjnkFeZBR2J1nKWq2/Vqfi6o9d1m0yqzZCrZ68t0ihOj+wtgbAeBE7jQaiFetyxDwPsXP5LX871v2ZN5SkQmnfsJq/JSIVOrJCtrTCZP4yGuDkE1ituTTRbL0jihS/VU/LqXt8+h6lJpuXcsEZ37GOTClvtxVXb0hZQGGmHoHH7QMZ0qXaVBEhb8eIjcj92VgQos2QhmWwA/nQ== alex.callejas@isengard.mx.redhat.com"}'
    register: gce

  - name: Save hosts data within a group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instances_temp
    with_items: "{{ gce.instance_data }}"

  - name: Wait for ssh to come up
    wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
    with_items: "{{ gce.instance_data }}"

  - name: Setting ip as instance fact
    set_fact: host={{ item.public_ip }}
    with_items: "{{ gce.instance_data }}"

- name: Configure instance post-creation
  hosts: gce_instances_temp
  gather_facts: True
  remote_user: dark_axl
  become: yes
  become_method: sudo

  roles:

    - myapache
