---
  #Playbook to delete instances, balancer and configurations
- name: Playbook to clean gce instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ["Set here the email account"]
    credentials_file: ["Put here the credentials file .json"]
    project_id: ["Put here your ID Project"]
    instance_names: ["Put here the name of instances to create"]


  tasks:
    - name: Delete gce load balancer
      gce_lb:
        name: lbserver
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

    - name: Delete gce instances
      gce:
        instance_names: "{{ instance_names }}"
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"

    - name: Delete firewall rule
      gce_net:
        name: default
        fwname: "my-http-fw-rule"
        state: absent
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
