---
- name: Set hostname
  hosts: servers
  tasks:

    - name: Add Satellite host
      lineinfile:
        path: /etc/hosts
        line: ["Set here your ip for your Satellite host"]
        state: present
